using BluetoothBatteryWidget.Core.Models;
using WpfColor = System.Windows.Media.Color;

namespace BluetoothBatteryWidget.App.Services;

public sealed record ColorPreset(
    string Id,
    string Label,
    WpfColor PrimaryText,
    WpfColor SecondaryText,
    WpfColor BatteryText,
    WpfColor CardTint,
    WpfColor CardBorder,
    WpfColor Track,
    WpfColor IconBack,
    WpfColor IconBorder,
    WpfColor FooterTop,
    WpfColor FooterBottom,
    WpfColor ListTop,
    WpfColor ListBottom,
    WpfColor ActionButtonBack,
    WpfColor ActionButtonBorder)
{
    public override string ToString() => Label;
}

public static class ColorPresetCatalog
{
    public static IReadOnlyList<ColorPreset> Presets { get; } =
    [
        new(
            WidgetSettings.WhiteBluePreset,
            "화이트 블루",
            ColorFrom("#10243C"),
            ColorFrom("#314E6A"),
            ColorFrom("#132F4D"),
            ColorFrom("#C2FFFFFF"),
            ColorFrom("#93FFFFFF"),
            ColorFrom("#7AB8C8D7"),
            ColorFrom("#E7F2F8FC"),
            ColorFrom("#A3CBDDEE"),
            ColorFrom("#C8FFFFFF"),
            ColorFrom("#ADECF7FF"),
            ColorFrom("#A7FFFFFF"),
            ColorFrom("#88ECF5FF"),
            ColorFrom("#B5F5FAFF"),
            ColorFrom("#9ECAE0EF")),
        new(
            WidgetSettings.DeepBlueSeaPreset,
            "딥 블루",
            ColorFrom("#0A2D54"),
            ColorFrom("#2E6696"),
            ColorFrom("#0F4F91"),
            ColorFrom("#C8E8F4FF"),
            ColorFrom("#93ABC8E5"),
            ColorFrom("#7A89A9C4"),
            ColorFrom("#DFF0FAFF"),
            ColorFrom("#8EAFCCE7"),
            ColorFrom("#C0DDF3FF"),
            ColorFrom("#A085B6DE"),
            ColorFrom("#B1E4F6FF"),
            ColorFrom("#8A6EA5D4"),
            ColorFrom("#B7D7F3FF"),
            ColorFrom("#84A7C8E8")),
        new(
            WidgetSettings.AblRedPreset,
            "아블 레드",
            ColorFrom("#FBEFF3"),
            ColorFrom("#E7B3C0"),
            ColorFrom("#FFC7D5"),
            ColorFrom("#C31A1017"),
            ColorFrom("#A64E2A36"),
            ColorFrom("#994A2836"),
            ColorFrom("#D7321C26"),
            ColorFrom("#B36E4557"),
            ColorFrom("#C22C1A26"),
            ColorFrom("#A4402634"),
            ColorFrom("#C7341F2B"),
            ColorFrom("#A8472A3B"),
            ColorFrom("#C167475B"),
            ColorFrom("#9C805A70")),
        new(
            WidgetSettings.GrassGreenPreset,
            "그래스 그린",
            ColorFrom("#163322"),
            ColorFrom("#2F7451"),
            ColorFrom("#1FA367"),
            ColorFrom("#C6E5F2E8"),
            ColorFrom("#93A8C7B2"),
            ColorFrom("#7892B49C"),
            ColorFrom("#DCF1F8F0"),
            ColorFrom("#8FB0C8B4"),
            ColorFrom("#B9DFF0E4"),
            ColorFrom("#A07AB091"),
            ColorFrom("#AFE1F2E6"),
            ColorFrom("#8B6AA583"),
            ColorFrom("#B4B9E4C8"),
            ColorFrom("#86A2C7AD")),
        new(
            WidgetSettings.BurgundyRedPreset,
            "버건디 레드",
            ColorFrom("#3D1325"),
            ColorFrom("#8A3B57"),
            ColorFrom("#B63254"),
            ColorFrom("#CDEEE7ED"),
            ColorFrom("#B694A9BE"),
            ColorFrom("#9A758CA5"),
            ColorFrom("#F1E9F0F6"),
            ColorFrom("#C39DB5CB"),
            ColorFrom("#DDCEC3D2"),
            ColorFrom("#C8A993BC"),
            ColorFrom("#E1D5C9DA"),
            ColorFrom("#C5A487BC"),
            ColorFrom("#CFD4B2C8"),
            ColorFrom("#AFA285BD")),
        new(
            WidgetSettings.DawnDarkPreset,
            "던 다크",
            ColorFrom("#ECF1F7"),
            ColorFrom("#C4CEDA"),
            ColorFrom("#F5F9FF"),
            ColorFrom("#B0141A23"),
            ColorFrom("#9C364558"),
            ColorFrom("#84314055"),
            ColorFrom("#D3182433"),
            ColorFrom("#A64B617A"),
            ColorFrom("#B1232D3B"),
            ColorFrom("#9B33465C"),
            ColorFrom("#B4293546"),
            ColorFrom("#A0374A63"),
            ColorFrom("#B4546A86"),
            ColorFrom("#8F6C84A3")),
        new(
            WidgetSettings.CyberDarkPreset,
            "사이버 다크",
            ColorFrom("#DDF4FF"),
            ColorFrom("#86C6EA"),
            ColorFrom("#8CE4FF"),
            ColorFrom("#BE111B2A"),
            ColorFrom("#A43A5A7C"),
            ColorFrom("#8E2D4B68"),
            ColorFrom("#D91A2B42"),
            ColorFrom("#A8507CA8"),
            ColorFrom("#C2263D5D"),
            ColorFrom("#A3375A85"),
            ColorFrom("#B22A4567"),
            ColorFrom("#98406A98"),
            ColorFrom("#BF4C7EB2"),
            ColorFrom("#966495C9")),
        new(
            WidgetSettings.OceanMistPreset,
            "Ocean Mist",
            ColorFrom("#0E2540"),
            ColorFrom("#2B567A"),
            ColorFrom("#113657"),
            ColorFrom("#C1F4FBFF"),
            ColorFrom("#98C9DBEE"),
            ColorFrom("#6CA3BAD0"),
            ColorFrom("#E4F2FAFF"),
            ColorFrom("#A0BCD3E5"),
            ColorFrom("#C4F3FBFF"),
            ColorFrom("#98DCEEFE"),
            ColorFrom("#A0F3FCFF"),
            ColorFrom("#79D1EBF8"),
            ColorFrom("#ADF0FAFF"),
            ColorFrom("#94BFD8E8")),
        new(
            WidgetSettings.SkyGlassPreset,
            "Sky Glass",
            ColorFrom("#112A45"),
            ColorFrom("#366184"),
            ColorFrom("#153B61"),
            ColorFrom("#C5F8FDFF"),
            ColorFrom("#9CCEE6F2"),
            ColorFrom("#73B8D4DF"),
            ColorFrom("#E9F7FDFF"),
            ColorFrom("#A9D4E9F4"),
            ColorFrom("#CEF6FEFF"),
            ColorFrom("#A8E8F8FF"),
            ColorFrom("#B2F6FEFF"),
            ColorFrom("#86DEEFFD"),
            ColorFrom("#B4F4FDFF"),
            ColorFrom("#A0D2E7F3")),
        new(
            WidgetSettings.MintBluePreset,
            "Mint Blue",
            ColorFrom("#12313F"),
            ColorFrom("#3A6E74"),
            ColorFrom("#1A4358"),
            ColorFrom("#C6FCF7F8"),
            ColorFrom("#9EDDD5DA"),
            ColorFrom("#79C8C0C8"),
            ColorFrom("#ECFBFAFB"),
            ColorFrom("#A8E0DFE3"),
            ColorFrom("#CDFCF8F9"),
            ColorFrom("#B7F4F0F2"),
            ColorFrom("#BFFCF7FA"),
            ColorFrom("#91EAE4EA"),
            ColorFrom("#BBFBF7FA"),
            ColorFrom("#A1DEDAE1")),
        new(
            WidgetSettings.SteelAquaPreset,
            "Steel Aqua",
            ColorFrom("#1D2A36"),
            ColorFrom("#4A637A"),
            ColorFrom("#2A4256"),
            ColorFrom("#C5F1F5F8"),
            ColorFrom("#9AB8CAD9"),
            ColorFrom("#7D9EB2C1"),
            ColorFrom("#EAF2F7FB"),
            ColorFrom("#A7BFD0DE"),
            ColorFrom("#C8EDF5FA"),
            ColorFrom("#A7D2E2EF"),
            ColorFrom("#B2ECF4FA"),
            ColorFrom("#88C1D5E5"),
            ColorFrom("#B2E8F2F9"),
            ColorFrom("#98B8CAD8")),
        new(
            WidgetSettings.BurgundyPreset,
            "Burgundy",
            ColorFrom("#2E1220"),
            ColorFrom("#5E3347"),
            ColorFrom("#7B2442"),
            ColorFrom("#CDFCF6FA"),
            ColorFrom("#BFA3B2C7"),
            ColorFrom("#8E9CADB8"),
            ColorFrom("#F6F1F6FA"),
            ColorFrom("#C3B3C3D4"),
            ColorFrom("#EEE6ECF5"),
            ColorFrom("#DCCFDCE7"),
            ColorFrom("#F3ECF2F8"),
            ColorFrom("#DFD0DDE9"),
            ColorFrom("#E4D8E5F0"),
            ColorFrom("#C2AABDD1")),
        new(
            WidgetSettings.CrimsonRedPreset,
            "Crimson Red",
            ColorFrom("#341017"),
            ColorFrom("#73313E"),
            ColorFrom("#A22436"),
            ColorFrom("#CEFDF7F8"),
            ColorFrom("#C9A7B0BB"),
            ColorFrom("#9AA0AEB7"),
            ColorFrom("#F9F5F6F9"),
            ColorFrom("#CCB7BEC8"),
            ColorFrom("#F3E6EAF0"),
            ColorFrom("#E4D3D9E3"),
            ColorFrom("#FAEEF0F4"),
            ColorFrom("#E7D9DDE5"),
            ColorFrom("#EDDEE3EC"),
            ColorFrom("#D0A9B6C4")),
        new(
            WidgetSettings.BlackTonePreset,
            "Black Tone",
            ColorFrom("#E8EEF5"),
            ColorFrom("#B7C2D1"),
            ColorFrom("#F3F6FA"),
            ColorFrom("#B320252D"),
            ColorFrom("#A0485668"),
            ColorFrom("#8A36495E"),
            ColorFrom("#DE202832"),
            ColorFrom("#B44C5D71"),
            ColorFrom("#C326313D"),
            ColorFrom("#B1364657"),
            ColorFrom("#D22A3340"),
            ColorFrom("#B7344252"),
            ColorFrom("#CC344454"),
            ColorFrom("#A6435568")),
        new(
            WidgetSettings.DeepGreenPreset,
            "Deep Green",
            ColorFrom("#112E23"),
            ColorFrom("#31634F"),
            ColorFrom("#1D7A59"),
            ColorFrom("#CAF5FBF6"),
            ColorFrom("#9EC8BDB3"),
            ColorFrom("#7EB2A39B"),
            ColorFrom("#E8F8F5F0"),
            ColorFrom("#A3C7BCB2"),
            ColorFrom("#D4F6F0E8"),
            ColorFrom("#B8E5DCCE"),
            ColorFrom("#DDF7F1E8"),
            ColorFrom("#B4DDCFBF"),
            ColorFrom("#CDEFE5D9"),
            ColorFrom("#9CC8BDAE")),
        new(
            WidgetSettings.CobaltBluePreset,
            "Cobalt Blue",
            ColorFrom("#102445"),
            ColorFrom("#365A91"),
            ColorFrom("#1F4FA8"),
            ColorFrom("#C9F2F7FF"),
            ColorFrom("#9CB7D7F0"),
            ColorFrom("#7C97C0DB"),
            ColorFrom("#E8F2FBFF"),
            ColorFrom("#9FB9D7F1"),
            ColorFrom("#CFEAFBFF"),
            ColorFrom("#A9D1EFFF"),
            ColorFrom("#D5EEFCFF"),
            ColorFrom("#98C6E7FA"),
            ColorFrom("#C1E6FBFF"),
            ColorFrom("#9FBEDDDF"))
    ];

    public static ColorPreset GetById(string? presetId)
    {
        var normalized = WidgetSettings.NormalizeColorPresetId(presetId);
        return Presets.First(preset => string.Equals(preset.Id, normalized, StringComparison.Ordinal));
    }

    private static WpfColor ColorFrom(string value)
    {
        return (WpfColor)System.Windows.Media.ColorConverter.ConvertFromString(value);
    }
}

