using BluetoothBatteryWidget.Core.Models;

namespace BluetoothBatteryWidget.App.Services;

public sealed record UiLanguageOption(string Id, string Label);

public sealed record UiLanguageText(
    string SettingsTitle,
    string AutostartLabel,
    string CloseToTrayLabel,
    string GuidedProbeLabel,
    string AggressivePolicyLabel,
    string UiScaleLabel,
    string ColorPresetLabel,
    string LanguageLabel,
    string RefreshNowButton,
    string DeveloperContactButton,
    string SupportButtonLabel,
    string UpdateButton,
    string UpdateChecking,
    string UpdateNoUpdate,
    string UpdateAssetMissing,
    string UpdateReleaseReadFailed,
    string UpdateChecksumMissing,
    string UpdateSourceNotTrusted,
    string UpdateDownloading,
    string UpdateDownloadingFormat,
    string UpdateVerifying,
    string UpdateVerificationFailed,
    string UpdateSignatureFailed,
    string UpdateDownloadFailed,
    string UpdateInstallStarting,
    string UpdateInstallLaunchFailed,
    string ExitButton,
    string StatusPanelToggleTooltip,
    string StatusPanelCollapseTooltip,
    string SettingsTooltip,
    string CloseTooltip,
    string OpenWidgetTray,
    string RefreshNowTray,
    string ExitTray,
    string VersionPrefix,
    string ConnectingText,
    string UnsupportedText,
    string DiagnosticsConnectedLabel,
    string DiagnosticsBatteryReadLabel,
    string DiagnosticsMatchedLabel,
    string DiagnosticsUnsupportedLabel,
    string StatusRefreshing,
    string StatusUpdatedPrefix,
    string StatusRefreshTimeout,
    string StatusRefreshFailed,
    string DiagnosticsRefreshSkipped,
    string ProbeAlreadyHasBattery,
    string ProbeConnectionInfoMissing,
    string ProbeOtherProbeRunning,
    string ProbeStart,
    string ProbeGuided,
    string ProbeSuccessDefault,
    string ProbeFailureDefault,
    string ProbeCancelled,
    string ProbeException,
    string ProbeCalibrationRawMissing,
    string ProbeCalibrationNotPossible,
    string ProbeCalibrationSaved,
    string PerformanceModeLiteStatus,
    string VisualModeLite,
    string VisualModeNormal,
    string DeveloperContactTitle,
    string DeveloperContactCopiedFormat,
    string DeveloperContactCopyFailed,
    string IconImageSelectTitle,
    string IconImageFilter,
    string IconAdjustFallbackMessage,
    string IconAdjustFallbackTitle,
    string InlineIconChange,
    string InlineRestoreDefault,
    string InlineCancel,
    string InlineSave);

public static class UiLanguageCatalog
{
    public static IReadOnlyList<UiLanguageOption> Options { get; } =
    [
        new(WidgetSettings.KoreanLanguage, "한국어"),
        new(WidgetSettings.EnglishLanguage, "English"),
        new(WidgetSettings.JapaneseLanguage, "日本語"),
        new(WidgetSettings.ChineseSimplifiedLanguage, "简体中文"),
        new(WidgetSettings.ChineseTraditionalLanguage, "繁體中文"),
        new(WidgetSettings.LatinLanguage, "Latina"),
        new(WidgetSettings.FrenchLanguage, "Français")
    ];

    public static UiLanguageText Get(string? language)
    {
        return WidgetSettings.NormalizeLanguage(language) switch
        {
            WidgetSettings.EnglishLanguage => English,
            WidgetSettings.JapaneseLanguage => Japanese,
            WidgetSettings.ChineseSimplifiedLanguage => ChineseSimplified,
            WidgetSettings.ChineseTraditionalLanguage => ChineseTraditional,
            WidgetSettings.LatinLanguage => Latin,
            WidgetSettings.FrenchLanguage => French,
            _ => Korean
        };
    }

    public static string BuildDiagnosticsSummary(string? language, int connected, int batteryRead, int matched, int unsupported)
    {
        var text = Get(language);
        return $"{text.DiagnosticsConnectedLabel}: {connected} | {text.DiagnosticsBatteryReadLabel}: {batteryRead} | {text.DiagnosticsMatchedLabel}: {matched} | {text.DiagnosticsUnsupportedLabel}: {unsupported}";
    }

    public static string BuildUpdatedStatus(string? language, DateTime now)
    {
        var text = Get(language);
        return $"{text.StatusUpdatedPrefix} {now:HH:mm:ss}";
    }

    private static readonly UiLanguageText English = new(
        SettingsTitle: "Settings",
        AutostartLabel: "Run at Windows startup",
        CloseToTrayLabel: "Keep in tray when closing",
        GuidedProbeLabel: "Guided capture",
        AggressivePolicyLabel: "Third-party aggressive mode",
        UiScaleLabel: "UI size/font",
        ColorPresetLabel: "Color preset",
        LanguageLabel: "Language",
        RefreshNowButton: "Refresh now",
        DeveloperContactButton: "Contact developer",
        SupportButtonLabel: "Support",
        UpdateButton: "Update",
        UpdateChecking: "Checking latest version...",
        UpdateNoUpdate: "You already have the latest version.",
        UpdateAssetMissing: "Update file (setup.exe) was not found in the latest release.",
        UpdateReleaseReadFailed: "Could not check the latest release.",
        UpdateChecksumMissing: "Checksum file (setup.exe.sha256) was not found in the latest release.",
        UpdateSourceNotTrusted: "Update source check failed.",
        UpdateDownloading: "Downloading update...",
        UpdateDownloadingFormat: "Downloading update... {0}%",
        UpdateVerifying: "Verifying downloaded update...",
        UpdateVerificationFailed: "Update verification failed. Download was blocked.",
        UpdateSignatureFailed: "Update signature check failed.",
        UpdateDownloadFailed: "Update download failed.",
        UpdateInstallStarting: "Download complete. Restarting app to install update...",
        UpdateInstallLaunchFailed: "Could not launch installer.",
        ExitButton: "Exit",
        StatusPanelToggleTooltip: "Collapse/expand status panel",
        StatusPanelCollapseTooltip: "Collapse status panel",
        SettingsTooltip: "Settings",
        CloseTooltip: "Close",
        OpenWidgetTray: "Open widget",
        RefreshNowTray: "Refresh now",
        ExitTray: "Exit",
        VersionPrefix: "Version",
        ConnectingText: "Connecting",
        UnsupportedText: "Unsupported",
        DiagnosticsConnectedLabel: "Connected",
        DiagnosticsBatteryReadLabel: "Battery read",
        DiagnosticsMatchedLabel: "Matched",
        DiagnosticsUnsupportedLabel: "Unsupported",
        StatusRefreshing: "Refreshing...",
        StatusUpdatedPrefix: "Updated",
        StatusRefreshTimeout: "Refresh delayed (timeout). Retry on next cycle.",
        StatusRefreshFailed: "Refresh failed.",
        DiagnosticsRefreshSkipped: "Skipped this cycle due to connection query delay",
        ProbeAlreadyHasBattery: "Battery value already exists.",
        ProbeConnectionInfoMissing: "Connection info not found.",
        ProbeOtherProbeRunning: "Another probe is running.",
        ProbeStart: "Probe started...",
        ProbeGuided: "Guided input... Move buttons/sticks for 2 seconds.",
        ProbeSuccessDefault: "Probe complete",
        ProbeFailureDefault: "Probe failed.",
        ProbeCancelled: "Probe cancelled.",
        ProbeException: "Exception during probe processing.",
        ProbeCalibrationRawMissing: "Raw data for calibration was not found.",
        ProbeCalibrationNotPossible: "Calibration requires model key and raw value.",
        ProbeCalibrationSaved: "Saved 100% calibration anchor. Rechecking value.",
        PerformanceModeLiteStatus: "Performance mode: Lite Glass",
        VisualModeLite: "Lite Glass",
        VisualModeNormal: "Normal Glass",
        DeveloperContactTitle: "Developer contact",
        DeveloperContactCopiedFormat: "Email copied: {0}",
        DeveloperContactCopyFailed: "Failed to copy email.",
        IconImageSelectTitle: "Select icon image",
        IconImageFilter: "Image files (*.png;*.jpg;*.jpeg;*.bmp)|*.png;*.jpg;*.jpeg;*.bmp|All files (*.*)|*.*",
        IconAdjustFallbackMessage: "Could not open image adjust dialog. Applying selected image directly.\nPNG/JPG/BMP is recommended.",
        IconAdjustFallbackTitle: "Icon image",
        InlineIconChange: "Change icon",
        InlineRestoreDefault: "Restore default",
        InlineCancel: "Cancel",
        InlineSave: "Save");

    private static readonly UiLanguageText Korean = English with
    {
        SettingsTitle = "설정",
        AutostartLabel = "윈도우 시작 시 실행",
        CloseToTrayLabel = "닫기 시 트레이 유지",
        GuidedProbeLabel = "키 입력 유도",
        AggressivePolicyLabel = "서드파티 인식 강화",
        UiScaleLabel = "UI 크기/폰트",
        ColorPresetLabel = "색상 프리셋",
        LanguageLabel = "언어",
        RefreshNowButton = "지금 새로 고침",
        DeveloperContactButton = "개발자 문의",
        SupportButtonLabel = "후원하기",
        ExitButton = "종료",
        StatusPanelToggleTooltip = "상태 패널 접기/펼치기",
        StatusPanelCollapseTooltip = "상태 패널 접기",
        SettingsTooltip = "설정",
        CloseTooltip = "닫기",
        OpenWidgetTray = "위젯 열기",
        RefreshNowTray = "지금 새로 고침",
        ExitTray = "종료",
        VersionPrefix = "버전",
        ConnectingText = "연결중",
        UnsupportedText = "미지원",
        DiagnosticsConnectedLabel = "연결",
        DiagnosticsBatteryReadLabel = "배터리읽기",
        DiagnosticsMatchedLabel = "매칭",
        DiagnosticsUnsupportedLabel = "미지원",
        StatusRefreshing = "새로 고침 중...",
        StatusUpdatedPrefix = "업데이트",
        StatusRefreshTimeout = "새로 고침이 지연되었습니다. 다음 주기에 다시 시도합니다.",
        StatusRefreshFailed = "새로 고침에 실패했습니다.",
        DiagnosticsRefreshSkipped = "연결 조회 지연으로 이번 주기를 건너뜀",
        ProbeAlreadyHasBattery = "이미 배터리 값이 있습니다.",
        ProbeConnectionInfoMissing = "연결 정보를 찾지 못했습니다.",
        ProbeOtherProbeRunning = "다른 기기 수집이 진행 중입니다.",
        ProbeStart = "수집 시작...",
        ProbeGuided = "입력 유도 중... 2초간 버튼/스틱을 조작해 주세요.",
        ProbeSuccessDefault = "수집 완료",
        ProbeFailureDefault = "수집에 실패했습니다.",
        ProbeCancelled = "수집이 취소되었습니다.",
        ProbeException = "수집 처리 중 예외가 발생했습니다.",
        ProbeCalibrationRawMissing = "보정용 원시 데이터를 찾지 못했습니다.",
        ProbeCalibrationNotPossible = "모델 키와 원시값이 없어 보정할 수 없습니다.",
        ProbeCalibrationSaved = "100% 기준 보정을 저장했습니다. 값을 다시 확인합니다.",
        PerformanceModeLiteStatus = "성능 모드: 라이트 글래스",
        VisualModeLite = "라이트 글래스",
        VisualModeNormal = "일반 글래스",
        DeveloperContactTitle = "개발자 문의",
        DeveloperContactCopiedFormat = "이메일이 복사되었습니다: {0}",
        DeveloperContactCopyFailed = "이메일 복사에 실패했습니다.",
        IconImageSelectTitle = "아이콘 이미지 선택",
        IconImageFilter = "이미지 파일 (*.png;*.jpg;*.jpeg;*.bmp)|*.png;*.jpg;*.jpeg;*.bmp|모든 파일 (*.*)|*.*",
        IconAdjustFallbackMessage = "이미지 미리 조절을 열지 못했습니다. 선택한 이미지를 바로 적용합니다.\nPNG/JPG/BMP 파일을 권장합니다.",
        IconAdjustFallbackTitle = "아이콘 이미지",
        InlineIconChange = "아이콘 변경",
        InlineRestoreDefault = "기본값 복원",
        InlineCancel = "취소",
        InlineSave = "저장"
    };

    private static readonly UiLanguageText Japanese = English with
    {
        SettingsTitle = "設定",
        AutostartLabel = "Windows 起動時に実行",
        CloseToTrayLabel = "閉じる時にトレイへ",
        GuidedProbeLabel = "入力ガイド収集",
        AggressivePolicyLabel = "サードパーティ攻撃モード",
        UiScaleLabel = "UI サイズ/フォント",
        ColorPresetLabel = "カラープリセット",
        LanguageLabel = "言語",
        RefreshNowButton = "今すぐ更新",
        DeveloperContactButton = "開発者に連絡",
        SupportButtonLabel = "支援する",
        ExitButton = "終了",
        StatusPanelToggleTooltip = "ステータスを折りたたむ/展開",
        StatusPanelCollapseTooltip = "ステータスを折りたたむ",
        SettingsTooltip = "設定",
        CloseTooltip = "閉じる",
        OpenWidgetTray = "ウィジェットを開く",
        RefreshNowTray = "今すぐ更新",
        ExitTray = "終了",
        VersionPrefix = "バージョン",
        ConnectingText = "接続中",
        UnsupportedText = "未対応",
        DiagnosticsConnectedLabel = "接続",
        DiagnosticsBatteryReadLabel = "バッテリー取得",
        DiagnosticsMatchedLabel = "一致",
        DiagnosticsUnsupportedLabel = "未対応",
        StatusRefreshing = "更新中...",
        StatusUpdatedPrefix = "更新",
        StatusRefreshTimeout = "更新が遅延しました。次の周期で再試行します。",
        StatusRefreshFailed = "更新に失敗しました。",
        DeveloperContactTitle = "開発者連絡",
        DeveloperContactCopiedFormat = "メールをコピーしました: {0}",
        DeveloperContactCopyFailed = "メールのコピーに失敗しました。",
        IconImageSelectTitle = "アイコン画像を選択",
        IconAdjustFallbackTitle = "アイコン画像",
        InlineIconChange = "アイコン変更",
        InlineRestoreDefault = "初期値に戻す",
        InlineCancel = "キャンセル",
        InlineSave = "保存"
    };

    private static readonly UiLanguageText ChineseSimplified = English with
    {
        SettingsTitle = "设置",
        AutostartLabel = "开机自动运行",
        CloseToTrayLabel = "关闭时保留到托盘",
        GuidedProbeLabel = "引导采集",
        AggressivePolicyLabel = "第三方激进模式",
        UiScaleLabel = "UI 大小/字体",
        ColorPresetLabel = "颜色预设",
        LanguageLabel = "语言",
        RefreshNowButton = "立即刷新",
        DeveloperContactButton = "联系开发者",
        SupportButtonLabel = "赞助",
        ExitButton = "退出",
        StatusPanelToggleTooltip = "折叠/展开状态面板",
        StatusPanelCollapseTooltip = "折叠状态面板",
        SettingsTooltip = "设置",
        CloseTooltip = "关闭",
        OpenWidgetTray = "打开小组件",
        RefreshNowTray = "立即刷新",
        ExitTray = "退出",
        VersionPrefix = "版本",
        ConnectingText = "连接中",
        UnsupportedText = "不支持",
        DiagnosticsConnectedLabel = "连接",
        DiagnosticsBatteryReadLabel = "电量读取",
        DiagnosticsMatchedLabel = "匹配",
        DiagnosticsUnsupportedLabel = "不支持",
        StatusRefreshing = "刷新中...",
        StatusUpdatedPrefix = "更新",
        StatusRefreshTimeout = "刷新延迟，将在下个周期重试。",
        StatusRefreshFailed = "刷新失败。",
        DeveloperContactTitle = "开发者联系",
        DeveloperContactCopiedFormat = "邮箱已复制: {0}",
        DeveloperContactCopyFailed = "邮箱复制失败。",
        IconImageSelectTitle = "选择图标图片",
        IconAdjustFallbackTitle = "图标图片",
        InlineIconChange = "更换图标",
        InlineRestoreDefault = "恢复默认",
        InlineCancel = "取消",
        InlineSave = "保存"
    };

    private static readonly UiLanguageText ChineseTraditional = English with
    {
        SettingsTitle = "設定",
        AutostartLabel = "開機自動執行",
        CloseToTrayLabel = "關閉時保留到系統匣",
        GuidedProbeLabel = "引導收集",
        AggressivePolicyLabel = "第三方激進模式",
        UiScaleLabel = "UI 大小/字型",
        ColorPresetLabel = "顏色預設",
        LanguageLabel = "語言",
        RefreshNowButton = "立即重新整理",
        DeveloperContactButton = "聯絡開發者",
        SupportButtonLabel = "贊助",
        ExitButton = "結束",
        StatusPanelToggleTooltip = "摺疊/展開狀態面板",
        StatusPanelCollapseTooltip = "摺疊狀態面板",
        SettingsTooltip = "設定",
        CloseTooltip = "關閉",
        OpenWidgetTray = "開啟小工具",
        RefreshNowTray = "立即重新整理",
        ExitTray = "結束",
        VersionPrefix = "版本",
        ConnectingText = "連線中",
        UnsupportedText = "不支援",
        DiagnosticsConnectedLabel = "連線",
        DiagnosticsBatteryReadLabel = "電量讀取",
        DiagnosticsMatchedLabel = "匹配",
        DiagnosticsUnsupportedLabel = "不支援",
        StatusRefreshing = "重新整理中...",
        StatusUpdatedPrefix = "更新",
        StatusRefreshTimeout = "重新整理延遲，將於下個週期重試。",
        StatusRefreshFailed = "重新整理失敗。",
        DeveloperContactTitle = "聯絡開發者",
        DeveloperContactCopiedFormat = "已複製 Email: {0}",
        DeveloperContactCopyFailed = "Email 複製失敗。",
        IconImageSelectTitle = "選擇圖示圖片",
        IconAdjustFallbackTitle = "圖示圖片",
        InlineIconChange = "更換圖示",
        InlineRestoreDefault = "還原預設",
        InlineCancel = "取消",
        InlineSave = "儲存"
    };

    private static readonly UiLanguageText Latin = English with
    {
        SettingsTitle = "Optiones",
        AutostartLabel = "Exsecutio ad initium Windows",
        CloseToTrayLabel = "In area notificationis serva cum clauditur",
        GuidedProbeLabel = "Collectio ducta",
        AggressivePolicyLabel = "Modus aggressivus tertiae partis",
        UiScaleLabel = "Magnitudo UI/fontis",
        ColorPresetLabel = "Praeset coloris",
        LanguageLabel = "Lingua",
        RefreshNowButton = "Nunc refice",
        DeveloperContactButton = "Contactus auctoris",
        SupportButtonLabel = "Sustine",
        ExitButton = "Exi",
        StatusPanelToggleTooltip = "Panelum status contrahere/expandere",
        StatusPanelCollapseTooltip = "Panelum status contrahere",
        SettingsTooltip = "Optiones",
        CloseTooltip = "Claude",
        OpenWidgetTray = "Widget aperi",
        RefreshNowTray = "Nunc refice",
        ExitTray = "Exi",
        VersionPrefix = "Versio",
        ConnectingText = "Coniungens",
        UnsupportedText = "Non sustinetur",
        DiagnosticsConnectedLabel = "Conexae",
        DiagnosticsBatteryReadLabel = "Batteria lecta",
        DiagnosticsMatchedLabel = "Concordatae",
        DiagnosticsUnsupportedLabel = "Non sustinetur",
        StatusRefreshing = "Reficiens...",
        StatusUpdatedPrefix = "Renovatum",
        StatusRefreshTimeout = "Refectio tarda (tempus finitum). In proximo cyclo iterabitur.",
        StatusRefreshFailed = "Refectio defecit.",
        DeveloperContactTitle = "Contactus auctoris",
        DeveloperContactCopiedFormat = "Epistula electronica copiata: {0}",
        DeveloperContactCopyFailed = "Copia epistulae defecit.",
        IconImageSelectTitle = "Elige imaginem iconis",
        IconAdjustFallbackTitle = "Imago iconis",
        InlineIconChange = "Muta iconem",
        InlineRestoreDefault = "Restitue initium",
        InlineCancel = "Cancella",
        InlineSave = "Serva"
    };

    private static readonly UiLanguageText French = English with
    {
        SettingsTitle = "Paramètres",
        AutostartLabel = "Lancer au démarrage de Windows",
        CloseToTrayLabel = "Garder dans la zone de notification à la fermeture",
        GuidedProbeLabel = "Collecte guidée",
        AggressivePolicyLabel = "Mode agressif tiers",
        UiScaleLabel = "Taille UI/police",
        ColorPresetLabel = "Préréglage de couleur",
        LanguageLabel = "Langue",
        RefreshNowButton = "Rafraîchir maintenant",
        DeveloperContactButton = "Contacter le développeur",
        SupportButtonLabel = "Soutenir",
        ExitButton = "Quitter",
        StatusPanelToggleTooltip = "Replier/déplier le panneau d'état",
        StatusPanelCollapseTooltip = "Replier le panneau d'état",
        SettingsTooltip = "Paramètres",
        CloseTooltip = "Fermer",
        OpenWidgetTray = "Ouvrir le widget",
        RefreshNowTray = "Rafraîchir maintenant",
        ExitTray = "Quitter",
        VersionPrefix = "Version",
        ConnectingText = "Connexion",
        UnsupportedText = "Non pris en charge",
        DiagnosticsConnectedLabel = "Connectés",
        DiagnosticsBatteryReadLabel = "Batterie lue",
        DiagnosticsMatchedLabel = "Appariés",
        DiagnosticsUnsupportedLabel = "Non pris en charge",
        StatusRefreshing = "Rafraîchissement...",
        StatusUpdatedPrefix = "Mis à jour",
        StatusRefreshTimeout = "Rafraîchissement retardé (timeout). Nouvelle tentative au prochain cycle.",
        StatusRefreshFailed = "Échec du rafraîchissement.",
        DeveloperContactTitle = "Contacter le développeur",
        DeveloperContactCopiedFormat = "Email copié: {0}",
        DeveloperContactCopyFailed = "Échec de la copie de l'email.",
        IconImageSelectTitle = "Sélectionner l'image d'icône",
        IconAdjustFallbackTitle = "Image d'icône",
        InlineIconChange = "Changer l'icône",
        InlineRestoreDefault = "Restaurer par défaut",
        InlineCancel = "Annuler",
        InlineSave = "Enregistrer"
    };
}
